### ISSUE TITLE
Issue with Reka Web

### ISSUE THREAD

**Issue by umegbewe** [MeNsaaH/reka#15]
Testing out the binary version of reka

Ran on the terminal :
```
reka web
```
Output:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ede811]

goroutine 1 [running]:
github.com/mensaah/reka/web/models.SetDB(0x0)
        /home/runner/work/reka/reka/web/models/models.go:19 +0x51
github.com/mensaah/reka/cmd.glob..func4(0x329eb40, 0x32e02e0, 0x0, 0x0)
        /home/runner/work/reka/reka/cmd/web.go:47 +0x45
github.com/spf13/cobra.(*Command).execute(0x329eb40, 0x32e02e0, 0x0, 0x0, 0x329eb40, 0x32e02e0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x329e600, 0x44578a, 0x3223320, 0xc00006e778)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/mensaah/reka/cmd.Execute()
        /home/runner/work/reka/reka/cmd/root.go:101 +0x31
main.main()
        /home/runner/work/reka/reka/main.go:21 +0x25
```

**Comment by MeNsaaH** [comment]
Hi @umegbewe , I've currently stalled a bit on reka. Got my hands full and was down for a while. I'll pick it back up As soon as I can.
